projects:
  zupshotapi:
    schemaPath: src/graphql/schema.json
    includes:
      - '**/*.graphql'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: src/graphql/API.js
        docsFilePath: src/graphql
  zupshot:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
